//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference_Organization_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivitiesMain()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int id { get; set; }
        public int EventName_Id { get; set; }
        public int Winner_Id { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public int DayOfStart { get; set; }
        public System.TimeSpan TimeOfStart { get; set; }
    
        public virtual EventNames EventNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
