//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference_Organization_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsMain
    {
        public int id { get; set; }
        public int EventName_Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CountOfDays { get; set; }
        public int City_Id { get; set; }
        public string Photo_Name { get; set; }
        public byte[] Photo_Image { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual EventNames EventNames { get; set; }
    }
}
