//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference_Organization_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id { get; set; }
        public int ActivitiesMain_Id { get; set; }
        public int ActivityName_Id { get; set; }
        public int DayOfStart { get; set; }
        public System.TimeSpan TimeOfStart { get; set; }
        public int Moderator_Id { get; set; }
        public Nullable<int> Judge_1_Id { get; set; }
        public Nullable<int> Judge_2_Id { get; set; }
        public Nullable<int> Judge_3_Id { get; set; }
        public Nullable<int> Judge_4_Id { get; set; }
        public Nullable<int> Judge_5_Id { get; set; }
    
        public virtual ActivitiesMain ActivitiesMain { get; set; }
        public virtual ActivityNames ActivityNames { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Users Users3 { get; set; }
        public virtual Users Users4 { get; set; }
        public virtual Users Users5 { get; set; }
    }
}
